adding initial proto file
PlunderKnowledge/nifty-messenger pull request #3
Opened 2018-05-10 00:15 UTC by grubino

What else should go in here?

2018-05-10 02:43 UTC, recursivelycurious commented
@grubino see comments on #2 - some context would be helpful. One general note; if necessary to facilitate exploration and discussion, I believe its valid to have a project be private initially and open it at an appropriate alpha/beta stage. Not sure if that is needed here, but wanted to mention in case the sparseness of the repo / issues / commit logs is due to playing close to the vest rather than lack of clarity?

2018-05-10 02:44 UTC, recursivelycurious requested changes
More information and context please.

2018-05-10 15:56 UTC, grubino commented
I will add a README soon @recursivelycurious

2018-05-10 18:34 UTC, grubino commented
Added more README stuffs.

2018-05-10 18:38 UTC, grubino commented on README.md
> +Contributors to ñIFTy Messenger should be aware that any and all code to be merged into a release branch is subject to review by ñIFT members.
"will be subject to review prior to merging"

2018-05-11 18:31 UTC, grubino commented
k, it's been long enough.  Merging...

2018-05-11 18:31 UTC, merged